# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('g4emma', '0005_auto_20171212_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(default=datetime.datetime(2017, 12, 12, 22, 7, 48, 563240, tzinfo=utc), max_length=255),
        ),
    ]
