# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('g4emma', '0006_auto_20171212_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(default=datetime.datetime(2017, 12, 12, 22, 9, 0, 996736, tzinfo=utc), max_length=255),
        ),
    ]
